/**
 * engine/worldModel/v2_1/evidenceCatalogV21.js
 *
 * World Model v2.1 — Frozen Atomic Evidence Catalog (Stage19A1).
 *
 * SHADOW ONLY. Static data tables; NO inference, NO signal extraction,
 * NO dimension scoring, NO response-validity, NO displayPosition.
 *
 * Primary authority for evidenceId / construct / direction / distortionType /
 * semanticProposition:
 *   R3 §D — docs/RC8.3_STAGE18_R3_WORLD_OS_CONTRACT_REPAIR.md
 *   (48 normalized atomic evidence, 65 → 48 merge/split).
 *
 * Derived traceability metadata (sourceQuestionIds / supportingOptionIds /
 * counterOptionIds) is derived ONLY from R1 §C/D (option → proposition →
 * evidence) plus R3 §D merge/split rationale. Where authority does not
 * uniquely define a field, it is set to null / [] and listed in
 * `unresolvedDerivedMetadata` — never guessed.
 *
 * Fields:
 *   - evidenceId, construct, direction (H|D|N), distortionType, semanticProposition
 *       → R3 §D verbatim (authority).
 *   - sourceQuestionIds    → questions whose options map to this evidence (R1 §C/D).
 *   - supportingOptionIds  → "questionId:optionId" strings that map to this evidence.
 *   - counterOptionIds     → [] UNRESOLVED (authority has no per-evidence counter mapping;
 *                            R1 §F contradicts[] is "—" for every evidence).
 *   - independenceGroup    → construct code (R1 §F independenceGroup column).
 *   - strengthClass        → null UNRESOLVED (R1 §F strength is per-18-evidence;
 *                            not uniquely preserved across the 65 → 48 merge).
 *   - nearNeighborRelations→ [] UNRESOLVED (R1 §B nearNeighbor is construct-level only).
 *
 * @version world_model_v2_1
 */

const ATOMIC_EVIDENCE_COUNT_V21 = 48

const EVIDENCE_CATALOG_V21 = [
  // ── DECISION (6) ────────────────────────────────────────────────────────
  {
    evidenceId: 'DEC_ACTION_LEARNS',
    construct: 'DECISION',
    direction: 'H',
    distortionType: null,
    semanticProposition: '行动本身制造信息',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_DEC_01', 'SC_DEC_02'],
    supportingOptionIds: ['SC_DEC_01:A', 'SC_DEC_02:B'],
    counterOptionIds: [],
    independenceGroup: 'DEC',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'DEC_INFO_VALUED',
    construct: 'DECISION',
    direction: 'H',
    distortionType: null,
    semanticProposition: '增量信息值得等待/寻求',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_DEC_02'],
    supportingOptionIds: ['SC_DEC_02:A'],
    counterOptionIds: [],
    independenceGroup: 'DEC',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'DEC_CERTAINTY_GATE',
    construct: 'DECISION',
    direction: 'D',
    distortionType: 'certainty-gate',
    semanticProposition: '决策必须先有确定性',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_DEC_01'],
    supportingOptionIds: ['SC_DEC_01:B'],
    counterOptionIds: [],
    independenceGroup: 'DEC',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'DEC_ANALYSIS_PARALYSIS',
    construct: 'DECISION',
    direction: 'D',
    distortionType: 'analysis-paralysis',
    semanticProposition: '决策必须先穷尽风险',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_DEC_01'],
    supportingOptionIds: ['SC_DEC_01:D'],
    counterOptionIds: [],
    independenceGroup: 'DEC',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'DEC_SOCIAL_PROOF',
    construct: 'DECISION',
    direction: 'D',
    distortionType: 'social-proof',
    semanticProposition: '他人确认优先于自有信息',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_DEC_01'],
    supportingOptionIds: ['SC_DEC_01:C'],
    counterOptionIds: [],
    independenceGroup: 'DEC',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'DEC_INFO_BLIND',
    construct: 'DECISION',
    direction: 'D',
    distortionType: 'info-blind',
    semanticProposition: '没意识到信息会改变判断',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_DEC_02'],
    supportingOptionIds: ['SC_DEC_02:C'],
    counterOptionIds: [],
    independenceGroup: 'DEC',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },

  // ── FEEDBACK (5) ────────────────────────────────────────────────────────
  {
    evidenceId: 'FB_PROCESSING',
    construct: 'FEEDBACK',
    direction: 'H',
    distortionType: null,
    semanticProposition: '反馈是信息，值得采集裁决',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_FB_01', 'SC_FB_02'],
    supportingOptionIds: ['SC_FB_01:A', 'SC_FB_02:A', 'SC_FB_02:D'],
    counterOptionIds: [],
    independenceGroup: 'FB',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'FB_AS_THREAT',
    construct: 'FEEDBACK',
    direction: 'D',
    distortionType: 'feedback-as-threat',
    semanticProposition: '反馈是对自我的威胁（防御）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_FB_02'],
    supportingOptionIds: ['SC_FB_02:B'],
    counterOptionIds: [],
    independenceGroup: 'FB',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'FB_AS_NOISE',
    construct: 'FEEDBACK',
    direction: 'D',
    distortionType: 'feedback-as-noise',
    semanticProposition: '外部反馈无信息量（信自己）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_FB_01', 'SC_FB_02'],
    supportingOptionIds: ['SC_FB_01:B', 'SC_FB_02:C'],
    counterOptionIds: [],
    independenceGroup: 'FB',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'FB_INERT',
    construct: 'FEEDBACK',
    direction: 'D',
    distortionType: 'feedback-inert',
    semanticProposition: '记下反馈但不据此改变',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_FB_01'],
    supportingOptionIds: ['SC_FB_01:D'],
    counterOptionIds: [],
    independenceGroup: 'FB',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'FB_SYMPATHY',
    construct: 'FEEDBACK',
    direction: 'D',
    distortionType: 'sympathy-seeking',
    semanticProposition: '只寻求顺耳的反馈',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_FB_01'],
    supportingOptionIds: ['SC_FB_01:C'],
    counterOptionIds: [],
    independenceGroup: 'FB',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },

  // ── PROBABILITY (6) ─────────────────────────────────────────────────────
  {
    evidenceId: 'PROB_BASE_RATE',
    construct: 'PROBABILITY',
    direction: 'H',
    distortionType: null,
    semanticProposition: '主动查基础率/失败案例',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_PROB_01'],
    supportingOptionIds: ['SC_PROB_01:A'],
    counterOptionIds: [],
    independenceGroup: 'PROB',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'PROB_UPDATABLE',
    construct: 'PROBABILITY',
    direction: 'H',
    distortionType: null,
    semanticProposition: '概率可随新信息更新',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_PROB_02'],
    supportingOptionIds: ['SC_PROB_02:A'],
    counterOptionIds: [],
    independenceGroup: 'PROB',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'PROB_SURVIVOR_BIAS',
    construct: 'PROBABILITY',
    direction: 'D',
    distortionType: 'survivor-bias',
    semanticProposition: '采信/复制幸存者个例',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_PROB_01'],
    supportingOptionIds: ['SC_PROB_01:B', 'SC_PROB_01:C'],
    counterOptionIds: [],
    independenceGroup: 'PROB',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'PROB_BINARY_FIXED',
    construct: 'PROBABILITY',
    direction: 'D',
    distortionType: 'fixed-prob',
    semanticProposition: '概率固定，不更新',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_PROB_02'],
    supportingOptionIds: ['SC_PROB_02:B'],
    counterOptionIds: [],
    independenceGroup: 'PROB',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'PROB_NO_RANGE',
    construct: 'PROBABILITY',
    direction: 'D',
    distortionType: 'no-range',
    semanticProposition: '无区间语言，凭感觉',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_PROB_02'],
    supportingOptionIds: ['SC_PROB_02:C'],
    counterOptionIds: [],
    independenceGroup: 'PROB',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'PROB_NO_AWARENESS',
    construct: 'PROBABILITY',
    direction: 'D',
    distortionType: 'no-awareness',
    semanticProposition: '无概率意识',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_PROB_01'],
    supportingOptionIds: ['SC_PROB_01:D'],
    counterOptionIds: [],
    independenceGroup: 'PROB',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },

  // ── RISK (6) ────────────────────────────────────────────────────────────
  {
    evidenceId: 'RISK_ASYMMETRY_AWARE',
    construct: 'RISK',
    direction: 'H',
    distortionType: null,
    semanticProposition: '感知风险不对称（赔率）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_RISK_01'],
    supportingOptionIds: ['SC_RISK_01:A'],
    counterOptionIds: [],
    independenceGroup: 'RISK',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'RISK_REVERSIBILITY_AWARE',
    construct: 'RISK',
    direction: 'H',
    distortionType: null,
    semanticProposition: '可逆性进入决策',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_RISK_02'],
    supportingOptionIds: ['SC_RISK_02:A'],
    counterOptionIds: [],
    independenceGroup: 'RISK',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'RISK_LOSS_AVERSION',
    construct: 'RISK',
    direction: 'D',
    distortionType: 'loss-aversion',
    semanticProposition: '只看到下行（过度回避）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_RISK_01'],
    supportingOptionIds: ['SC_RISK_01:B'],
    counterOptionIds: [],
    independenceGroup: 'RISK',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'RISK_UPSIDE_BLIND',
    construct: 'RISK',
    direction: 'D',
    distortionType: 'upside-blind',
    semanticProposition: '只看到上行（鲁莽）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_RISK_01'],
    supportingOptionIds: ['SC_RISK_01:C'],
    counterOptionIds: [],
    independenceGroup: 'RISK',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'RISK_BLIND',
    construct: 'RISK',
    direction: 'D',
    distortionType: 'risk-blind',
    semanticProposition: '无不对称意识',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_RISK_01'],
    supportingOptionIds: ['SC_RISK_01:D'],
    counterOptionIds: [],
    independenceGroup: 'RISK',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'RISK_REVERSIBILITY_BLIND',
    construct: 'RISK',
    direction: 'D',
    distortionType: 'reversibility-blind',
    semanticProposition: '把一切风险当作不可逆',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_RISK_02'],
    supportingOptionIds: ['SC_RISK_02:B', 'SC_RISK_02:C'],
    counterOptionIds: [],
    independenceGroup: 'RISK',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },

  // ── LEVERAGE (4) ────────────────────────────────────────────────────────
  {
    evidenceId: 'LEV_DECOUPLED',
    construct: 'LEVERAGE',
    direction: 'H',
    distortionType: null,
    semanticProposition: '价值可与个人时间解耦',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_LEV_01', 'SC_LEV_02'],
    supportingOptionIds: ['SC_LEV_01:B', 'SC_LEV_01:C', 'SC_LEV_02:B'],
    counterOptionIds: [],
    independenceGroup: 'LEV',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'LEV_LINEAR_EFFORT',
    construct: 'LEVERAGE',
    direction: 'D',
    distortionType: 'linear-effort',
    semanticProposition: '一次性线性交付',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_LEV_01'],
    supportingOptionIds: ['SC_LEV_01:A'],
    counterOptionIds: [],
    independenceGroup: 'LEV',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'LEV_TIME_COUPLED',
    construct: 'LEVERAGE',
    direction: 'D',
    distortionType: 'time-coupled',
    semanticProposition: '产出停手即停（时间耦合）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_LEV_02'],
    supportingOptionIds: ['SC_LEV_02:A'],
    counterOptionIds: [],
    independenceGroup: 'LEV',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'LEV_BLIND',
    construct: 'LEVERAGE',
    direction: 'D',
    distortionType: 'leverage-blind',
    semanticProposition: '从未想过放大/复用',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_LEV_01', 'SC_LEV_02'],
    supportingOptionIds: ['SC_LEV_01:D', 'SC_LEV_02:C'],
    counterOptionIds: [],
    independenceGroup: 'LEV',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },

  // ── TIME (4) ────────────────────────────────────────────────────────────
  {
    evidenceId: 'TIME_COMPOUNDING_PROTECTED',
    construct: 'TIME',
    direction: 'H',
    distortionType: null,
    semanticProposition: '保护复利时间',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_TIME_01'],
    supportingOptionIds: ['SC_TIME_01:B'],
    counterOptionIds: [],
    independenceGroup: 'TIME',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'TIME_COMPOUNDING_UNPROTECTED',
    construct: 'TIME',
    direction: 'D',
    distortionType: 'compounding-unprotected',
    semanticProposition: '长期时间被即时/忙碌挤压',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_TIME_01'],
    supportingOptionIds: ['SC_TIME_01:A', 'SC_TIME_01:C'],
    counterOptionIds: [],
    independenceGroup: 'TIME',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'TIME_DIRECTION_PERSISTENT',
    construct: 'TIME',
    direction: 'H',
    distortionType: null,
    semanticProposition: '方向持续投入',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_TIME_02'],
    supportingOptionIds: ['SC_TIME_02:A'],
    counterOptionIds: [],
    independenceGroup: 'TIME',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'TIME_DIRECTION_UNSTABLE',
    construct: 'TIME',
    direction: 'D',
    distortionType: 'direction-unstable',
    semanticProposition: '方向频繁切换/漂移',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_TIME_02'],
    supportingOptionIds: ['SC_TIME_02:B', 'SC_TIME_02:C'],
    counterOptionIds: [],
    independenceGroup: 'TIME',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },

  // ── IDENTITY (5) ────────────────────────────────────────────────────────
  {
    evidenceId: 'ID_UPDATEABLE',
    construct: 'IDENTITY',
    direction: 'H',
    distortionType: null,
    semanticProposition: '身份可更新（能力/越界）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_ID_01', 'SC_ID_02'],
    supportingOptionIds: ['SC_ID_01:A', 'SC_ID_01:C', 'SC_ID_02:B', 'SC_ID_02:C'],
    counterOptionIds: [],
    independenceGroup: 'ID',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'ID_BOUNDARY_FIXED',
    construct: 'IDENTITY',
    direction: 'D',
    distortionType: 'boundary-fixed',
    semanticProposition: '身份是固定边界（不像我）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_ID_01'],
    supportingOptionIds: ['SC_ID_01:B'],
    counterOptionIds: [],
    independenceGroup: 'ID',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'ID_ABILITY_FIXED',
    construct: 'IDENTITY',
    direction: 'D',
    distortionType: 'ability-fixed',
    semanticProposition: '能力固化（我可能做不好）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_ID_01'],
    supportingOptionIds: ['SC_ID_01:D'],
    counterOptionIds: [],
    independenceGroup: 'ID',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'ID_ROLE_FIXED',
    construct: 'IDENTITY',
    direction: 'D',
    distortionType: 'role-fixed',
    semanticProposition: '角色框架（我是 XX 职业）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_ID_02'],
    supportingOptionIds: ['SC_ID_02:A'],
    counterOptionIds: [],
    independenceGroup: 'ID',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'ID_CONTEXTUAL',
    construct: 'IDENTITY',
    direction: 'N',
    distortionType: null,
    semanticProposition: '情境框架（看对方）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_ID_02'],
    supportingOptionIds: ['SC_ID_02:D'],
    counterOptionIds: [],
    independenceGroup: 'ID',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },

  // ── OPPORTUNITY (5) ─────────────────────────────────────────────────────
  {
    evidenceId: 'OPP_DIVERSE',
    construct: 'OPPORTUNITY',
    direction: 'H',
    distortionType: null,
    semanticProposition: '多样化暴露带来机会',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_OPP_01', 'SC_OPP_02'],
    supportingOptionIds: ['SC_OPP_01:A', 'SC_OPP_02:A'],
    counterOptionIds: [],
    independenceGroup: 'OPP',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'OPP_NARROW',
    construct: 'OPPORTUNITY',
    direction: 'D',
    distortionType: 'narrow-exposure',
    semanticProposition: '接触面窄（熟悉/罕见）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_OPP_01'],
    supportingOptionIds: ['SC_OPP_01:B', 'SC_OPP_01:C'],
    counterOptionIds: [],
    independenceGroup: 'OPP',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'OPP_PASSIVE',
    construct: 'OPPORTUNITY',
    direction: 'D',
    distortionType: 'passive',
    semanticProposition: '被动等待机会',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_OPP_01'],
    supportingOptionIds: ['SC_OPP_01:D'],
    counterOptionIds: [],
    independenceGroup: 'OPP',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'OPP_HOMOGENEOUS',
    construct: 'OPPORTUNITY',
    direction: 'D',
    distortionType: 'homogeneous',
    semanticProposition: '接触人群同质化',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_OPP_02'],
    supportingOptionIds: ['SC_OPP_02:C'],
    counterOptionIds: [],
    independenceGroup: 'OPP',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'OPP_SOME',
    construct: 'OPPORTUNITY',
    direction: 'N',
    distortionType: null,
    semanticProposition: '接触多样性中等',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_OPP_02'],
    supportingOptionIds: ['SC_OPP_02:B'],
    counterOptionIds: [],
    independenceGroup: 'OPP',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },

  // ── SYSTEMS (7) ─────────────────────────────────────────────────────────
  {
    evidenceId: 'SYS_SYSTEM_CAUSALITY',
    construct: 'SYSTEMS',
    direction: 'H',
    distortionType: null,
    semanticProposition: '结构/情境因果观',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_SYS_01', 'SC_SYS_02'],
    supportingOptionIds: ['SC_SYS_01:A', 'SC_SYS_02:A'],
    counterOptionIds: [],
    independenceGroup: 'SYS',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'SYS_PERSON',
    construct: 'SYSTEMS',
    direction: 'D',
    distortionType: 'person-attribution',
    semanticProposition: '人事归因（是人不行）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_SYS_01'],
    supportingOptionIds: ['SC_SYS_01:B'],
    counterOptionIds: [],
    independenceGroup: 'SYS',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'SYS_EVENT',
    construct: 'SYSTEMS',
    direction: 'D',
    distortionType: 'event-attribution',
    semanticProposition: '事件归因（每次都不同）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_SYS_01'],
    supportingOptionIds: ['SC_SYS_01:C'],
    counterOptionIds: [],
    independenceGroup: 'SYS',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'SYS_METHOD',
    construct: 'SYSTEMS',
    direction: 'D',
    distortionType: 'method-attribution',
    semanticProposition: '方法归因（方法有漏洞）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_SYS_02'],
    supportingOptionIds: ['SC_SYS_02:B'],
    counterOptionIds: [],
    independenceGroup: 'SYS',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'SYS_LUCK',
    construct: 'SYSTEMS',
    direction: 'D',
    distortionType: 'luck-attribution',
    semanticProposition: '运气归因',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_SYS_02'],
    supportingOptionIds: ['SC_SYS_02:C'],
    counterOptionIds: [],
    independenceGroup: 'SYS',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'SYS_BRUTE_RETRY',
    construct: 'SYSTEMS',
    direction: 'D',
    distortionType: 'brute-retry',
    semanticProposition: '蛮力重试（不换方法）',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_SYS_02'],
    supportingOptionIds: ['SC_SYS_02:D'],
    counterOptionIds: [],
    independenceGroup: 'SYS',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
  {
    evidenceId: 'SYS_BLIND',
    construct: 'SYSTEMS',
    direction: 'D',
    distortionType: 'attribution-blind',
    semanticProposition: '无归因意识',
    derivedFrom: 'R1_SECTION_C_D_MAPPING',
    sourceQuestionIds: ['SC_SYS_01'],
    supportingOptionIds: ['SC_SYS_01:D'],
    counterOptionIds: [],
    independenceGroup: 'SYS',
    strengthClass: null,
    nearNeighborRelations: [],
    unresolvedDerivedMetadata: ['counterOptionIds', 'strengthClass', 'nearNeighborRelations'],
  },
]

module.exports = {
  ATOMIC_EVIDENCE_COUNT_V21,
  EVIDENCE_CATALOG_V21,
}
