/**
 * engine/worldModel/worldPrinciples.js
 *
 * RC8.3 Phase 1C — World Principles.
 *
 * These are the invariant rules that describe how the world works.
 * Every blind spot must be grounded in a specific world principle violation.
 *
 * Principles are NOT rules, NOT tips, NOT strategies.
 * They are DESCRIPTIVE — this is how reality operates, regardless of
 * whether anyone believes it or not.
 *
 * Design constraint:
 * - Must hold true regardless of occupation, income, country, or era
 * - Must be falsifiable
 * - Must describe a causal mechanism, not a correlation
 * - Must be usable for simulation (not just classification)
 *
 * @version world_model_v1
 */

const WORLD_PRINCIPLES = Object.freeze({

  // ═══════════════════════════════════════════════════════════════
  // Principle 1: Decision Creates Information
  // ═══════════════════════════════════════════════════════════════

  DECISION_CREATES_INFORMATION: {
    id: 'DECISION_CREATES_INFORMATION',
    label: '决策产生信息',
    statement:
      'Every decision that interacts with the world generates new information ' +
      'that was not available before the decision. Undecided options generate ' +
      'zero information. Delayed decisions delay the arrival of information.',
    mechanism:
      'When a person makes a choice and acts on it, the world responds. ' +
      'That response contains signal — data about what works, what does not, ' +
      'what the world rewards, what it punishes. Each decision is an experiment. ' +
      'Each experiment updates the person\'s internal model. Without decisions, ' +
      'the model cannot update.',
    consequence:
      'A person who delays decisions indefinitely is running an internal model ' +
      'that has stopped receiving new data. The model becomes stale. Its predictions ' +
      'become less accurate. Over time, the gap between the internal model and ' +
      'reality widens.',
    relatedBlindSpots: ['DECISION_INERTIA'],
    falsifiable:
      'If a person makes decisions but learns nothing from outcomes, then this ' +
      'principle alone is insufficient — the feedback principle must also hold.',
  },

  // ═══════════════════════════════════════════════════════════════
  // Principle 2: Feedback Updates Models
  // ═══════════════════════════════════════════════════════════════

  FEEDBACK_UPDATES_MODELS: {
    id: 'FEEDBACK_UPDATES_MODELS',
    label: '反馈更新模型',
    statement:
      'Action without systematic feedback collection does not update the internal ' +
      'model. The information generated by decisions is only useful if it is captured, ' +
      'interpreted, and integrated into future decisions.',
    mechanism:
      'The world sends signal. But signal only becomes information when it is ' +
      'observed, recorded, and processed. A person who acts but does not review ' +
      'outcomes is generating raw data that evaporates unused. Their internal model ' +
      'remains unchanged despite action.',
    consequence:
      'A person who acts frequently but never systematically reviews results may ' +
      'repeat the same mistakes indefinitely. Their model is frozen — not from ' +
      'lack of decisions, but from lack of feedback integration.',
    relatedBlindSpots: ['FEEDBACK_LOOP_GAP'],
    falsifiable:
      'If a person reviews outcomes but never changes behavior, then feedback ' +
      'exists but the model-update mechanism is broken at a different stage.',
  },

  // ═══════════════════════════════════════════════════════════════
  // Principle 3: Probability Governs Outcomes
  // ═══════════════════════════════════════════════════════════════

  PROBABILITY_GOVERNS_OUTCOMES: {
    id: 'PROBABILITY_GOVERNS_OUTCOMES',
    label: '概率支配结果',
    statement:
      'Most outcomes in complex systems are governed by probability distributions, ' +
      'not binary certainties. Thinking in terms of "will succeed" or "will fail" ' +
      'is a model error — the world operates in ranges, not points.',
    mechanism:
      'Any decision with uncertain outcomes has a distribution of possible results. ' +
      'Some outcomes are more likely, some less. The rational approach is to compare ' +
      'expected values, assess risk-reward asymmetries, and act accordingly. Binary ' +
      'thinking discards this distribution and collapses it to one point estimate.',
    consequence:
      'A person who thinks in binary terms either over-invests in "guaranteed" ' +
      'paths or rejects opportunities because they are not "certain." Both errors ' +
      'arise from the same model defect: inability to think probabilistically.',
    relatedBlindSpots: ['PROBABILITY_MISJUDGMENT'],
    falsifiable:
      'If a person can accurately estimate probabilities but systematically ' +
      'misjudges which risks are worth taking, the defect is in risk assessment, ' +
      'not probability estimation.',
  },

  // ═══════════════════════════════════════════════════════════════
  // Principle 4: Risk Is Asymmetrical
  // ═══════════════════════════════════════════════════════════════

  RISK_IS_ASYMMETRICAL: {
    id: 'RISK_IS_ASYMMETRICAL',
    label: '风险是不对称的',
    statement:
      'Risk is not uniform. Every decision has an asymmetric payoff structure: ' +
      'the downside and upside are rarely equal. Treating all risk as symmetrical ' +
      'danger leads to both excessive caution (missing asymmetric upside) and ' +
      'recklessness (ignoring catastrophic downside).',
    mechanism:
      'In most real-world decisions, the worst case and best case are not mirror ' +
      'images. Many opportunities have limited downside and potentially large upside. ' +
      'Many dangers have limited upside and potentially catastrophic downside. ' +
      'A functional risk model distinguishes between these.',
    consequence:
      'A person who treats all risk as dangerous avoids opportunities with positive ' +
      'asymmetry. A person who ignores downside takes risks with negative asymmetry. ' +
      'Both errors stem from the same root: not seeing the shape of risk.',
    relatedBlindSpots: ['RISK_MODEL_DISTORTION'],
    falsifiable:
      'If a person correctly assesses risk asymmetry but cannot act due to other ' +
      'constraints (identity, decision inertia), the risk model is functional but ' +
      'other models are broken.',
  },

  // ═══════════════════════════════════════════════════════════════
  // Principle 5: Leverage Multiplies Value
  // ═══════════════════════════════════════════════════════════════

  LEVERAGE_MULTIPLIES_VALUE: {
    id: 'LEVERAGE_MULTIPLIES_VALUE',
    label: '杠杆倍增价值',
    statement:
      'Value that is delivered in a one-to-one ratio (one unit of input → one unit ' +
      'of output) cannot scale beyond the individual\'s time and energy. Leverage ' +
      'is any mechanism that decouples output from personal input — allowing one ' +
      'unit of work to serve many recipients without proportional additional cost.',
    mechanism:
      'Leverage takes many forms: reusable assets (code, content, tools), systems ' +
      '(processes that run without the creator), networks (distribution that reaches ' +
      'many), and capital (money that works while you sleep). Without leverage, ' +
      'output is strictly bounded by personal capacity.',
    consequence:
      'A person who operates only through direct personal effort will hit a hard ' +
      'ceiling. Their world model does not include the concept that value can be ' +
      'amplified — so they never look for amplification mechanisms.',
    relatedBlindSpots: ['LEVERAGE_MODEL_GAP'],
    falsifiable:
      'If a person understands leverage but systematically chooses short-term ' +
      'direct rewards over long-term leverage building, the defect is in time ' +
      'preference, not leverage understanding.',
  },

  // ═══════════════════════════════════════════════════════════════
  // Principle 6: Time Compounds Advantage
  // ═══════════════════════════════════════════════════════════════

  TIME_COMPOUNDS_ADVANTAGE: {
    id: 'TIME_COMPOUNDS_ADVANTAGE',
    label: '时间复利优势',
    statement:
      'Activities whose value compounds over time — knowledge, relationships, ' +
      'reputation, systems, assets — produce outcomes that are not linear. Small ' +
      'consistent investments over long periods generate results that short-term ' +
      'optimization cannot match.',
    mechanism:
      'Compounding works because each period\'s gains become the base for the next ' +
      'period\'s gains. Skills built over years compound into expertise. Relationships ' +
      'built over years compound into trust networks. Short-term optimization sacrifices ' +
      'this compounding for immediate payoff.',
    consequence:
      'A person who systematically prioritizes immediate reward over compounding ' +
      'investment will find that others who started later but compounded longer ' +
      'eventually surpass them. The gap is not effort — it is time horizon.',
    relatedBlindSpots: ['TIME_HORIZON_TRAP'],
    falsifiable:
      'If a person invests consistently over long periods but chooses activities ' +
      'that do not compound (pure linear work), the time horizon is fine but ' +
      'the leverage model is absent.',
  },

  // ═══════════════════════════════════════════════════════════════
  // Principle 7: Identity Constrains Choices
  // ═══════════════════════════════════════════════════════════════

  IDENTITY_CONSTRAINS_CHOICES: {
    id: 'IDENTITY_CONSTRAINS_CHOICES',
    label: '身份约束选择',
    statement:
      'A person\'s identity — who they believe they are — acts as a filter on what ' +
      'choices they perceive as available. An identity that is rigid and role-bound ' +
      'filters out options that do not match the self-concept, even when those ' +
      'options are objectively available.',
    mechanism:
      'Identity is not just a description — it is a constraint system. Every "I am ' +
      'an X" statement also implies "I am not a Y." The set of implied negatives ' +
      'can be large and invisible to the person. A person who defines themselves ' +
      'narrowly has a narrow option set. A person who defines themselves ' +
      'expansively has an expansive option set.',
    consequence:
      'A person with rigid identity constraints may have all the information and ' +
      'resources needed for a path, but still not take it — because the path does ' +
      'not match their self-concept. This is not a knowledge gap; it is an ' +
      'identity gap.',
    relatedBlindSpots: ['IDENTITY_CONSTRAINT'],
    falsifiable:
      'If a person has a flexible identity but still cannot see available paths, ' +
      'the constraint is in opportunity exposure, not identity.',
  },

  // ═══════════════════════════════════════════════════════════════
  // Principle 8: Opportunity Emerges Through Exposure
  // ═══════════════════════════════════════════════════════════════

  OPPORTUNITY_EMERGES_THROUGH_EXPOSURE: {
    id: 'OPPORTUNITY_EMERGES_THROUGH_EXPOSURE',
    label: '机会通过暴露涌现',
    statement:
      'Opportunities are not equally visible to all observers. They emerge when ' +
      'a person\'s exposure — to people, ideas, environments, problems — intersects ' +
      'with their capability to recognize patterns. A person with narrow exposure ' +
      'has a narrow opportunity set, regardless of capability.',
    mechanism:
      'Opportunity recognition is a function of exposure surface area. The more ' +
      'diverse the inputs (people, domains, problems, tools), the more patterns ' +
      'the brain can match. Someone who only interacts with one domain and one ' +
      'set of people will only see opportunities visible within that domain.',
    consequence:
      'A highly capable person with narrow exposure will see fewer opportunities ' +
      'than a moderately capable person with broad exposure. The bottleneck is not ' +
      'skill — it is the surface area of the world they interact with.',
    relatedBlindSpots: ['OPPORTUNITY_BLINDNESS'],
    falsifiable:
      'If a person has broad exposure but cannot act on opportunities they see, ' +
      'the constraint is in decision model, risk model, or identity — not exposure.',
  },

  // ═══════════════════════════════════════════════════════════════
  // Principle 9: Systems Produce Emergent Behavior
  // ═══════════════════════════════════════════════════════════════

  SYSTEMS_PRODUCE_EMERGENT_BEHAVIOR: {
    id: 'SYSTEMS_PRODUCE_EMERGENT_BEHAVIOR',
    label: '系统产生涌现行为',
    statement:
      'Complex systems — economies, organizations, social networks, careers — ' +
      'produce outcomes that cannot be predicted by analyzing individual components ' +
      'in isolation. Interactions between components create emergent patterns. ' +
      'Linear causal thinking cannot model these systems.',
    mechanism:
      'In a system with feedback loops, delays, and nonlinear relationships, ' +
      'cause and effect are not always close in time or obvious in direction. ' +
      'A small input can produce a large output. A large input can produce ' +
      'nothing. Understanding systems requires thinking in loops, stocks, ' +
      'flows, and delays — not simple if-then chains.',
    consequence:
      'A person who thinks in linear cause-effect chains will consistently ' +
      'misdiagnose problems in complex systems. They will apply solutions that ' +
      'work in simple systems but fail in complex ones. They will be surprised ' +
      'by side effects and unintended consequences.',
    relatedBlindSpots: ['SYSTEM_THINKING_GAP'],
    falsifiable:
      'If a person understands system dynamics but cannot apply them due to ' +
      'lack of data or feedback, the defect is in feedback model, not systems ' +
      'thinking.',
  },

})

// ═══════════════════════════════════════════════════════════════
// UTILITY
// ═══════════════════════════════════════════════════════════════

function getPrincipleById(id) {
  return WORLD_PRINCIPLES[id] || null
}

function getPrinciplesForBlindSpot(blindSpotId) {
  var results = []
  Object.keys(WORLD_PRINCIPLES).forEach(function(key) {
    var p = WORLD_PRINCIPLES[key]
    if (p.relatedBlindSpots && p.relatedBlindSpots.indexOf(blindSpotId) >= 0) {
      results.push(p)
    }
  })
  return results
}

function getAllPrincipleIds() {
  return Object.keys(WORLD_PRINCIPLES)
}

module.exports = {
  WORLD_PRINCIPLES,
  getPrincipleById,
  getPrinciplesForBlindSpot,
  getAllPrincipleIds,
}
